Allow over-riding requirements path per project
freedomofpress/django_stack pull request #50
Opened 2019-01-08 18:50 UTC by msheiny

The requirements.txt path can vary per django project. Lets set a sane
default and allow over-ride via ansible variable.

2019-01-08 19:26 UTC, conorsch requested changes
Definitely a desirable config option, but CI is failing—appears that we need to bump Molecule. Can you take a look, @msheiny?

2019-01-08 19:43 UTC, msheiny commented
> Definitely a desirable config option, but CI is failing—appears that we need to bump Molecule. Can you take a look, @msheiny?

Sure thing! Re-runing through CI now :crossed_fingers:

2019-01-08 20:51 UTC, msheiny commented
passed @conorsch

2019-01-09 01:39 UTC, conorsch approved these changes

2019-01-09 01:39 UTC, merged